/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anaFidelis
 */
public class Principal extends javax.swing.JFrame {
    public PesquisaPrecosFacade pesquisa = new PesquisaPrecosFacade();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        pesquisa.ler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnPrincipal = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        edChavePesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbImagemLupa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCDs = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal.setBackground(new java.awt.Color(59, 174, 231));
        pnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Cordia New", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Consulta de preços");
        pnPrincipal.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        edChavePesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edChavePesquisa.setForeground(new java.awt.Color(102, 102, 102));
        edChavePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edChavePesquisaActionPerformed(evt);
            }
        });
        pnPrincipal.add(edChavePesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 453, -1));

        btPesquisar.setText("OK");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        pnPrincipal.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));
        pnPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 32, -1, -1));

        lbImagemLupa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win7U\\Documents\\trabalhoFinalProg2\\img\\lupa2.png")); // NOI18N
        pnPrincipal.add(lbImagemLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win7U\\Documents\\trabalhoFinalProg2\\img\\logoSubmarino.png")); // NOI18N
        pnPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 260, 190, 60));

        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordem crescente de valor", "Ordem decrescente de valor", "Ordem alfabética pelo nome do álbum e crescente de valor", "Ordem alfabética pelo nome do artista/banda e decrescente de valor" }));
        pnPrincipal.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 510, 20));

        tbCDs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbCDs.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tbCDs.setForeground(new java.awt.Color(102, 102, 102));
        tbCDs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo do CD", "Banda/Artista", "Valor", "Loja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbCDs);

        pnPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edChavePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edChavePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edChavePesquisaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        ArrayList<CD> result = new ArrayList();
        
        if (edChavePesquisa.getText() != "")
           result = (ArrayList<CD>) pesquisa.pesquisar(edChavePesquisa.getText());
        
        //aplica a ordenaçao
        Collections.sort(result);
        
        //para adicionar os valores na tabela
        DefaultTableModel modelo = (DefaultTableModel) tbCDs.getModel();
        modelo.setRowCount(0);
        
        for (CD cd : result){
            modelo.addRow(new Object[]{cd.getBanda(), cd.getTitulo(), cd.getPreco(), cd.getLoja()});
        }        
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JTextField edChavePesquisa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImagemLupa;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JTable tbCDs;
    // End of variables declaration//GEN-END:variables
}
